### ISSUE TITLE
Configuration file

### ISSUE THREAD

**Issue by DanielAndreasen** [MariaTsantaki/FASMA-synthesis#1]
Hi Maria,

We need to write about the configurations available.
Either we just write it in the `README.md` or we add a small documentation. Better do it a bit fast since people will be looking for this.

**Comment by MariaTsantaki** [comment]
I agree. A manual is needed.

**Comment by DanielAndreasen** [comment]
Great, the options are included in the `README.md`. Good job (I just changed the formatting a little, so it's easier to read).
I still think a real manual might be useful, explaining both the options (a small paragraph for each) with the defaults and the options.
We can write it together if you prefer :)
