### ISSUE TITLE
long paths for moog problem??

### ISSUE THREAD

**Issue by sousasag** [MariaTsantaki/FASMA-synthesis#18]
Hi,

When trying to install to give it a try I still find some problems when with long paths for the moog install.
I was trying in this folder:
"/home/sousasag/Programas/GIT_Projects/FASMA-synthesis/"
Then it worked out of the box when using a shorter path:
"/home/sousasag/Programas/FASMA-synthesis/"

I think it may be related with this line in your install script:

`printf $MOOGDATAPATH | awk 'BEGIN{RS="/";c=""} {if($RN>1) {printf ("     . %s\"/%s\"\n",c,$1);c="//"}}' >> FASMA/MOOG/Moogsilent.f`

**Comment by MariaTsantaki** [comment]
yes, you are right. This is an issue with MOOG we also came across. Apparently there is a limit in characters for the MOOG path. The above command should solve this. I tried in my PC with a very long path and it works.  

Also unfortunately the past months we made many changes in the installation and configuration files. Could it be that you have installed that bugged older commit without that command in? 
@DanielAndreasen what do you think?

**Comment by DanielAndreasen** [comment]
I think you might be right, Maria. I just tried cloning FASMA again, my path looks like this:
`/home/daniel/Documents/astro/a/very/long/path/goes/here/make/it/super/long/pleaaaaaasseeeee/FASMA-synthesis`.
The installation went fine, and when I ran `MOOGSILENT` (the executable in `FASMA/MOOG`), it prompted me for input files, so it seems to work. Sérgio, can you try to do `git pull`?

**Comment by sousasag** [comment]
Hi,
I did a fresh install on my laptop. Before I tried in my Desktop with Windows inside WSL...
Anyway, seems to be working in my laptop. But I was expecting to see the full path in Moogsilent.f. 
Instead there is only the local path to data/
Is this intended this way?

>       write (moogpath,1001)
>       moogpath = 
>      .  'data/'
> 

Cheers

**Comment by MariaTsantaki** [comment]
yes because there it reads the auxiliary files for the damping

**Comment by sousasag** [comment]
Before I remember to see the full path, but the problem was that it was spread in several lines, each line for each directory...

Good, Then it is fine, I close it. Good job ;)
