### ISSUE TITLE
Troubles in setting up the configuration file

### ISSUE THREAD

**Issue by LucaMalavolta** [MariaTsantaki/FASMA-synthesis#3]
Hi Maria,
Nice work, congratulation for the paper!
I have troubles in setting up the configuration file when I want to add the additional options, e.g. the 'model' keyword is not read and I cannot switch to the 'marcs' model - I have to modify synthDriver.py to make FASMA work. Could you provide some examples in the repository?
Cheers
Luca

**Comment by DanielAndreasen** [comment]
Hi Luca,
Can you please send an example of the configuration file? I will try to reproduce your issue then. And some of the error will be helpful too.
You should definitely not have to touch the `synthDriver.py`.

Cheers,
Daniel

**Comment by DanielAndreasen** [comment]
I just pushed some new commits. Can I ask you to pull again Luca, and try run

```
$ python synthDriver.py myConf.cfg
```

where the file `myConf.cfg` looks like this:

```
# this is a header (all special characters will act as header/comments)
giraffe_sun_arcturus_calib.lst
giraffe_sun_arcturus_calib.lst model:marcs
```
The two lines should give the same results, as I've changed the default model atmosphere to use is now `MARCS`. Before it was some we call `kurucz95` which are not provided (we are not allowed to share those, sorry).

**Comment by MariaTsantaki** [comment]
Hi Luca, 
Thanks for mentioning this. I uploaded a new version of marcs models, so please after you pull, untar them. Yeap we need to create a useful manual. If your config file is like this:

`# this is a header (all special characters will act as header/comments)`
`giraffe_sun_arcturus_calib.lst `

Then a synthetic spectrum will be created but not saved so probably it will not be useful. You probably need to save, view, or change the stellar parameters. So probably this will be better:

`# this is a header (all special characters will act as header/comments)`
`# linelist teff logg [M/H] vt vmac vsini options`
`giraffe_sun_arcturus_calib.lst 5777 4.44 0.0 1.0 3.21 1.9 save,plot`
`giraffe_sun_arcturus_calib.lst 5777 4.44 0.0 1.0 3.21 1.9 save,plot,resolution:115000`
`giraffe_sun_arcturus_calib.lst 5777 4.44 0.0 1.0 3.21 1.9 observations:Sun_HARPS.fits,resolution:115000,minimize,plot`

Now 1) a solar synthetic spectrum will be plotted and saved at results folder without a resolution broadening, 2)  a solar synthetic spectrum will be plotted and saved at results folder with a resolution of 115000, 3) the code will find best fit parameters for the spectrum which is at the spectra folder and save the results in the synthresults.dat file. 

Hopefully this will work. :)

**Comment by LucaMalavolta** [comment]
Hi Maria, Daniel,
Thank you very much for the quick feedback, yhe examples you provided all work! 
Specifcally, my problem was just a wrong use of the '':  I tried 'model':'marcs' and model:'marcs', but I didn't try model:marcs. The README is a bit misleading on this matter!
Cheers
Luca

**Comment by DanielAndreasen** [comment]
Hi Luca,

I just pushed a new version of the README without the quotes. I agree it was a bit confusing.
Let us know if you have any other problems.

Cheers,
Daniel
