### ISSUE TITLE
Regarding Kurucz model support

### ISSUE THREAD

**Issue by LucaMalavolta** [MariaTsantaki/FASMA-synthesis#4]
Hi Maria, Daniel
I think you should bring back the support to Kurucz models (kurucz95 and more importantly kurucz08). Actually, it would be very useful to extend the support to alpha enhanced models. I understand that you are not allowed to *post* the atmosphere models, but that doesn't mean you are not *allowed* to support them, as many other programs (starting from MOOG itself) do. It was quite easy for me to download the models from the official website and format them as required by FASMA, so even if you don't provided them most of the users will still be happy of the support (even more if you provide a script to do the conversion). 
Cheers

**Comment by DanielAndreasen** [comment]
Okay, I can see the use in this. We have a grid of kurucz95 which we are restricted to circulate. I can honestly not remember where the '08 came from.
In `utils.py` we write the grid points. Maybe this should be in a separate file which a user can easily adapt.

I talked with Maria yesterday about removing the Kurucz model atmospheres, as we don't ship them with FASMA, and it might be confusing. Will add them back later today.

Cheers,
Daniel

**Comment by LucaMalavolta** [comment]
The '08 refers to the models computed with the new opacity distributions (see astro-ph/0405087 ), they came out in 2004 and then updated in 2008, you can recognize them by the tag 'ODFNEW'. They are the most used one, in fact they are the ones I downloaded and converted by myself, so please be sure to fully support them (I remember I had to do a very quick bugfix)! The same models have been computed with enhanced alpha elements ('AODFNEW'), which are quite important for archeochemistry and population II studies.
Cheers
Luca

**Comment by DanielAndreasen** [comment]
Please pull the latest version. `kurucz08` is supported (thank you git!). If it works, then either close this issue or report back.

Cheers,
Daniel
